apiVersion: batch/v1
kind: CronJob
metadata:
  name: compare-models-job
spec:
  schedule: "0 3 * * *"  # every day at 3AM
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: compare-models
            image: your-docker-repo/compare-models:latest
            args:
              - "--model_name=my_forecast_model"
              - "--metric_name=rmse"
              - "--mode=min"
              - "--improvement_threshold=0.02"
            env:
            - name: AZURE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: azure-credentials
                  key: client-id
            - name: AZURE_TENANT_ID
              valueFrom:
                secretKeyRef:
                  name: azure-credentials
                  key: tenant-id
            - name: AZURE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: azure-credentials
                  key: client-secret
            - name: AZURE_SUBSCRIPTION_ID
              value: your-subscription-id
            - name: AZURE_RESOURCE_GROUP
              value: your-resource-group
            - name: AZURE_WORKSPACE_NAME
              value: your-workspace-name
          restartPolicy: OnFailure
