experiment_name: "time_series_xgboost_optuna"
model_params:                                 # Default XGBoost parameters if hyperparameter tuning is False
  objective: reg:squarederror
  # eval_metric: rmse
  max_depth: 6
  learning_rate: 0.1
  subsample: 0.8
  colsample_bytree: 0.8
  lambda: 1.0
  alpha: 0.0
features:
  - rolling_mean_7
  - rolling_mean_14
target: sales
data_path: "data/final_sales_data"
data_format: "parquet"
model_output_path: "models/baseline_xgb_pd_hp_model.pkl"
tune_hyperparameters: true                    # Set to true to enable Optuna tuning

