experiment_name: "time_series_xgboost"
model_params:
  num_boost_round: 100
  max_depth: 5
  learning_rate: 0.1
  objective: "reg:squarederror"
  random_state: 42
train_params:
  test_size: 0.2
  shuffle: False
  random_state: 42
  early_stopping_rounds: 20
features:
  - rolling_mean_7
  - rolling_mean_14
target: sales
data_path: "data/processed/final_sales_data_val"
data_format: "parquet"
model_output_path: "models/baseline_xgb_pd_model.pkl"
